name: build-executable
run-name: Build executable
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: "main.py"
          exe_path: "dist"
          options: "-F"
          upload_exe_with_name: "wuwa-fps-unlocker.exe"
