name: build-executable
run-name: Build executable
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wuwa-fps-unlocker
          path: dist
